# Generated by Django 5.0.7 on 2024-07-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_user_is_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_sub_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vacation',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
