# Generated by Django 5.0.7 on 2024-07-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_user_is_sub_manager_vacation_is_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
